config/routes.rb
Rails.application.routes.draw do
  resources :flights
  resources :tbos

end

app/models/flight.rb
class Flight < ActiveRecord::Base

  before_save :write_total
  after_save :update_tbo
  before_update :update_total
  after_update :update_totals
  after_destroy :update_totals


  private
  def write_total
    self.total = Flight.sum(:hours)        +
                 Flight.sum(:minutes)/60   +
                 Flight.sum(:seconds)/3600 +
                 self.hours                +
                 self.minutes/60           +
                 self.seconds/3600
  end

  def update_total
    self.total = Flight.where("id < #{self.id}").sum(:hours)        +
                 Flight.where("id < #{self.id}").sum(:minutes)/60   +
                 Flight.where("id < #{self.id}").sum(:seconds)/3600 +
                 self.hours                                         +
                 self.minutes/60                                    +
                 self.seconds/3600
  end

  def update_totals
    flights = Flight.where("id > #{self.id}")
    flights.each do |flight|
      flight.total = Flight.where("id <= #{flight.id}").sum(:total)
      flight.save
    end
  end

  def update_tbo
    tbos = Tbo.all
    tbos.each do |tbo|
      tbo.remaining_time = tbo.tbo - Flight.last.total
      tbo.elapsed_time = Flight.last.total
      tbo.save
    end
  end
end

app/models/tbo.rb
class Tbo < ActiveRecord::Base
  before_update :update_remaining_time
  private
  def update_remaining_time
    self.remaining_time = self.tbo - self.elapsed_time
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.all
  end

  def new
    # render(:text=>params)
    @flight = Flight.new
  end

  def show
    # render(:text=>params[:id])
    @flight = Flight.find(params[:id])
  end

  def edit
    # render(:text=>params[:id])
    @flight = Flight.find(params[:id])
  end

  def update
    # render(:text=>params)
    flight = Flight.find(params[:id])
    flight.update(flight_params)
    redirect_to flight_path(flight)
  end

  def create
    # render(:text=>params)
    flight = Flight.new(flight_params)
    flight.save
    redirect_to flight_path(flight)
  end

  def destroy
    # render(:text=>params)
    flight = Flight.find(params[:id])
    flight.destroy
    redirect_to flights_path
  end

  protected
  def flight_params
    params.require(:flight).permit(:hours, :minutes, :seconds, :total)
  end
end

app/controllers/tbos_controller.rb
class TbosController < ApplicationController
  def index
    @tbos = Tbo.all
  end

  def new
    @tbo = Tbo.new
  end

  def show
    # render(:text=>params[:id])
    @tbo = Tbo.find(params[:id])
  end

  def edit
    # render(:text=>params)
    @tbo = Tbo.find(params[:id])
  end

  def create
    # render(:text=>params[:tbo])
    tbo = Tbo.new(tbo_params)
    tbo.save
    # render(:text=>"ok")
    redirect_to tbo_path(tbo)
  end

  def update
    # render(:text=>params[:id])
    tbo = Tbo.find(params[:id])
    tbo.update(tbo_params)
    redirect_to tbo_path(tbo)
  end

  def destroy
    # render(:text=>params)
    tbo = Tbo.find(params[:id])
    tbo.destroy
    redirect_to tbos_path
  end

  private
  def tbo_params
    params.require(:tbo).permit(:name, :part_number, :tbo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/tbos_helper.rb
module TbosHelper
end

app/views/flights/edit.html.erb
<%= form_for @flight  do |f|%>
    <%= f.label(:hours, "Horas") %>
    <%= f.number_field(:hours) %>
    <%= f.label(:minutes, "Minutos") %>
    <%= f.number_field(:minutes) %>
    <%= f.label(:seconds, "Segundos") %>
    <%= f.number_field(:seconds) %>
    <%= f.submit(:Enviar) %>
<% end %>
<%= link_to("Indice", flights_path) %>

app/views/flights/index.html.erb
<table>
  <thead>
    <tr>
      <th>Horas</th>
      <th>Minutos</th>
      <th>Segundos</th>
      <th>Total</th>
      <th>Editar</th>
      <th>Mostrar</th>
      <th>Borrar</th>
    </tr>
  </thead>
  <tbody>
    <% @flights.each do |flight| %>
        <tr>
          <td><%= flight.hours %></td>
          <td><%= flight.minutes %></td>
          <td><%= flight.seconds %></td>
          <td><%= flight.total %></td>
          <td><%= link_to("Editar", edit_flight_path(flight)) %></td>
          <td><%= link_to("Mostrar", flight_path(flight)) %></td>
          <td><%= link_to("Borrar", flight_path(flight), method: :delete) %></td>
        </tr>
  <% end %>
  </tbody>
</table>

<%= link_to("Nuevo vuelo", new_flight_path) %>

app/views/flights/new.html.erb
<%= form_for @flight  do |f|%>
    <%= f.label(:hours, "Horas") %>
    <%= f.number_field(:hours) %> <br>
    <%= f.label(:minutes, "Minutos") %>
    <%= f.number_field(:minutes) %> <br>
    <%= f.label(:seconds, "Segundos") %>
    <%= f.number_field(:seconds) %> <br>
    <%= f.submit(:Enviar) %>
<% end %>
<%= link_to("indice", flights_path) %>

app/views/flights/show.html.erb
Horas:
<%= @flight.hours %> <br>
Minutos
<%= @flight.minutes %> <br>
Segundos
<%= @flight.seconds %> <br>
<%= link_to("Editar", edit_flight_path(@flight)) %> <br>
<%= link_to("Lista de vuelos", flights_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Condor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tbos/edit.html.erb
<%= form_for @tbo do |f| %>
    <%= f.label(:name, "Componente") %>
    <%= f.text_field(:name) %> <br>

    <%= f.label(:part_number, "Numero de parte") %>
    <%= f.text_field(:part_number) %> <br>

    <%= f.label(:tbo, "TBO") %>
    <%= f.number_field(:tbo) %> <br>

    <%= f.submit(:Guardar) %>

<% end %>

<%= link_to("Lista de TBOs", tbos_path) %>

app/views/tbos/index.html.erb
<h3>Lista de TBOs</h3>
<table>
  <thead>
      <tr>
        <th>Nombre</th>
        <th>Numero de parte</th>
        <th>Tbo</th>
        <th>Tiempo transcurrido</th>
        <th>Tiempo restante</th>
        <th>Editar</th>
        <th>Borrar</th>
        <th>Mostrar</th>
      </tr>
  </thead>
  <tbody>
    <% @tbos.each do |tbo| %>
        <tr>
          <td><%= tbo.name %></td>
          <td><%= tbo.part_number %></td>
          <td><%= tbo.tbo %></td>
          <td><%= tbo.elapsed_time %></td>
          <td><%= tbo.remaining_time %></td>
          <td><%= link_to("Etitar", edit_tbo_path(tbo)) %></td>
          <td><%= link_to("Borrar", tbo_path(tbo), method: :delete) %></td>
          <td><%= link_to("Mostrar", tbo_path(tbo)) %></td>
          <td></td>
          <td></td>
        </tr>
  <% end %>
  </tbody>
</table>
<%= link_to("Nuevo TBO", new_tbo_path ) %>

app/views/tbos/new.html.erb
<%= form_for @tbo do |f| %>
    <%= f.label(:name, "Componente") %>
    <%= f.text_field(:name) %> <br>

    <%= f.label(:part_number, "Numero de parte") %>
    <%= f.text_field(:part_number) %> <br>

    <%= f.label(:tbo, "TBO") %>
    <%= f.number_field(:tbo) %> <br>

    <%= f.submit(:Guardar) %>

<% end %>

app/views/tbos/show.html.erb
Nombre: <%= @tbo.name %> <br>
Numero de parte: <%= @tbo.part_number %> <br>
Tbo: <%= @tbo.tbo %> <br>
<%= link_to("Editar", edit_tbo_path(@tbo)) %> <br>
<%= link_to("Lista de TBOs", tbos_path) %>